// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8v8pYMf99a4dTiQ2Mda2OMgBgCYRTwYA',
    appId: '1:386593840323:web:37f39a723ffc419084d676',
    messagingSenderId: '386593840323',
    projectId: 'sih-tourist-app',
    authDomain: 'sih-tourist-app.firebaseapp.com',
    storageBucket: 'sih-tourist-app.firebasestorage.app',
    measurementId: 'G-JWP8E7CEE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtX5mgE9sUA6W0ACDPJrCegR7Lb4X9DrU',
    appId: '1:386593840323:android:99aa90813443b5e484d676',
    messagingSenderId: '386593840323',
    projectId: 'sih-tourist-app',
    storageBucket: 'sih-tourist-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDn6TFON7pqYe1xm3pfxTdfvgQf2u9SLM',
    appId: '1:386593840323:ios:f3572adcec59f05584d676',
    messagingSenderId: '386593840323',
    projectId: 'sih-tourist-app',
    storageBucket: 'sih-tourist-app.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDn6TFON7pqYe1xm3pfxTdfvgQf2u9SLM',
    appId: '1:386593840323:ios:f3572adcec59f05584d676',
    messagingSenderId: '386593840323',
    projectId: 'sih-tourist-app',
    storageBucket: 'sih-tourist-app.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8v8pYMf99a4dTiQ2Mda2OMgBgCYRTwYA',
    appId: '1:386593840323:web:baa789e6b09f341e84d676',
    messagingSenderId: '386593840323',
    projectId: 'sih-tourist-app',
    authDomain: 'sih-tourist-app.firebaseapp.com',
    storageBucket: 'sih-tourist-app.firebasestorage.app',
    measurementId: 'G-EK7NLVV4BS',
  );
}
